### ISSUE TITLE
Change name to turf-spatialjoin or turf-spatial-join

### ISSUE THREAD

**Issue by lyzidiamond** [Turfjs/turf-tag#3]
Because I don't know what tag is, and this does a spatial join. Thoughts?

**Comment by morganherlocker** [comment]
The tag name came from a couple other GIS engines I was familiar with that contained this exact same function. "spatial join" is very loaded in my experience, with everyone having a slightly different definition and expectations. I would like to stay away from the "JOIN" phrasing entirely, since people will expect it to be just like SQL, when this not really the same thing. Calling it a spatial join sets the expectation that it [does all of this stuff](http://revenant.ca/www/postgis/workshop/joins.html), when it actually does not do any of those things 1:1.

\my 2 cents

**Comment by lyzidiamond** [comment]
Point taken! Closing. :+1: :smile:
